version: "3"
services:
          mini-node-exporter:
                    build:
                              context: ./mini-node-exporter
                    container_name: mini-node-exporter
                    image: mini-node-exporter
                    ports:
                              - "23333:23333"
          prometheus:
                    container_name: prometheus-mne
                    image: prom/prometheus
                    ports:
                              - "9090:9090"
                    command: --config.file=/etc/prometheus/prometheus.yaml
                    volumes:
                              - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
          grafana:
                    image: grafana/grafana:5.0.4
                    ports:
                              - "3000:3000"
                    environment:
                              - GF_AUTH_BASIC_ENABLED=false
                              - GF_AUTH_ANONYMOUS_ENABLED=true
                              - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
